Algoritmo "semnome"
// Leia 3 números inteiros e calcule a multiplicação entre eles.
Var
   n1,n2,n3, multiplicao : inteiro


Inicio

   escreva("Digite o primeiro número: ")
   leia(n1)
   
   escreva("Digite o segundo número: ")
   leia(n2)
   
   escreva("Digite o terceiro número: ")
   leia(n3)

   multiplicao <- n1 * n2 * n3

   escreval("O resultado da multiplicação é: ", multiplicao)
Fimalgoritmo