Algoritmo "semnome"
// Leia 3 números e calcule: (primeiro número + terceiro número) * segundo número
Var
   num1, num2, num3, resultado : real
Inicio

   escreva("Digite o primeiro número: ")
   leia(num1)

   escreva("Digite o segundo número: ")
   leia(num2)

   escreva("Digite o terceiro número: ")
   leia(num3)

   resultado <- (num1 + num3) * num2

   escreval("O resultado é: ", resultado:6:2)

Fimalgoritmo